<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
		<LangVersion>7.3</LangVersion>
        <RootNamespace></RootNamespace>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>disable</Nullable>
		<ConsoleEncoding>UTF-8</ConsoleEncoding>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <DebugType>portable</DebugType>
        <DebugSymbols>true</DebugSymbols>
        <GenerateDependencyFile>true</GenerateDependencyFile>
        <!-- NuGet 打包暂不启用
        <PackageId>JLGames.RabbitClient</PackageId>
        <Authors>xuzhuoxi</Authors>
        <Description>A C# client library for discovering Rabbit-Server via Rabbit-Home and exchanging socket messages.</Description>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
        -->
    </PropertyGroup>

<!--    <ItemGroup>-->
<!--      <PackageReference Include="Portable.BouncyCastle" Version="1.9.0" />-->
<!--    </ItemGroup>-->
    
    <ItemGroup>
      <ProjectReference Include="..\..\Infra-CSharp\Infra-CSharp\Infra-CSharp.csproj" />
    </ItemGroup>

</Project>
