//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by ExcelExporter
//     version 2.0
//     from https://github.com/xuzhuoxi/ExcelExporter 
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLGames.RabbitClient.Server.MMO
{
    public static class ProtoMMOCode
    {   
        /// <summary>
        /// 房间不存在
        /// </summary>
        public const int MMORoomExist = -101;
        /// <summary>
        /// 房间已存在
        /// </summary>
        public const int MMORoomNotExist = -102;
        /// <summary>
        /// 房间容量上限
        /// </summary>
        public const int MMORoomCapLimit = -103;
        /// <summary>
        /// 团队不存在
        /// </summary>
        public const int MMOTeamCorpsExist = -104;
        /// <summary>
        /// 团队已存在
        /// </summary>
        public const int MMOTeamCorpsNotExist = -105;
        /// <summary>
        /// 团队容量上限
        /// </summary>
        public const int MMOTeamCorpsCapLimit = -106;
        /// <summary>
        /// 队伍不存在
        /// </summary>
        public const int MMOTeamExist = -107;
        /// <summary>
        /// 队伍已存在
        /// </summary>
        public const int MMOTeamNotExist = -108;
        /// <summary>
        /// 队伍容量上限
        /// </summary>
        public const int MMOTeamCapLimit = -109;
        /// <summary>
        /// 频道不存在
        /// </summary>
        public const int MMOChanExist = -110;
        /// <summary>
        /// 频道已存在
        /// </summary>
        public const int MMOChanNotExist = -111;
        /// <summary>
        /// 频道容量上限
        /// </summary>
        public const int MMOChanCapLimit = -112;
        /// <summary>
        /// 用户已存在
        /// </summary>
        public const int MMOPlayerExist = -113;
        /// <summary>
        /// 用户不存在
        /// </summary>
        public const int MMOPlayerNotExist = -114;
        /// <summary>
        /// 用户已经在房间中
        /// </summary>
        public const int MMOPlayerInRoom = -115;
        /// <summary>
        /// 单位已存在
        /// </summary>
        public const int MMOUnitExist = -116;
        /// <summary>
        /// 单位不存在
        /// </summary>
        public const int MMOUnitNotExist = -117;
        /// <summary>
        /// 索引类型不匹配
        /// </summary>
        public const int MMOIndexType = -200;
        /// <summary>
        /// 其它错误
        /// </summary>
        public const int MMOOther = -201;
    }
}