//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by ExcelExporter
//     version 2.2
//     from https://github.com/xuzhuoxi/ExcelExporter 
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLGames.RabbitClient.Server.MMO
{
    /// <summary>
    /// Variable key constants for room entities.
    /// 房间实体的变量键常量。
    /// </summary>
    public static class RoomVarKeys
    {   
        /// <summary>
        /// Room display name (string).
        /// 房间名称(string)
        /// </summary>
        public const string Name = "rn";
    }
}
