//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by ExcelExporter
//     version 2.2
//     from https://github.com/xuzhuoxi/ExcelExporter 
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLGames.RabbitClient.Server.MMO
{
    public static class UnitVarKeys
    {   
        /// <summary>
        /// 拥有者
        /// </summary>
        public const string Owner = "ow";
        /// <summary>
        /// 所有房间Id
        /// </summary>
        public const string Room = "rm";
        /// <summary>
        /// int32数组;坐标X、坐标Y、坐标Z
        /// </summary>
        public const string Pos = "pos";
        /// <summary>
        /// 朝向，int16
        /// </summary>
        public const string Toward = "tw";
        /// <summary>
        /// int32数组;输入X、输入Y、输入Z
        /// </summary>
        public const string InputMove = "im";
        /// <summary>
        /// int32数组;目标X、目标Y、目标Z
        /// </summary>
        public const string InputTarget = "it";
        /// <summary>
        /// 输入状态, Jump(bool)
        /// </summary>
        public const string InputJump = "ij";
        /// <summary>
        /// 动作状态(uint32)
        /// </summary>
        public const string ActionState = "as";
    }
}